# Generated by Django 4.2.16 on 2024-12-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_score'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 5)), name='score_between_1_and_5'),
        ),
    ]
