# Generated by Django 4.2.16 on 2024-12-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_on',
        ),
    ]
