# Generated by Django 4.2.16 on 2024-12-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_remove_review_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
