# Generated by Django 4.2.16 on 2024-12-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_review_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='default-value'),
        ),
    ]
