# Generated by Django 4.2.16 on 2024-12-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
