# Generated by Django 4.2.16 on 2024-12-10 20:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_alter_review_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default', max_length=255, verbose_name='image'),
        ),
    ]
